# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-30 01:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50, verbose_name='Event Name')),
                ('event_date', models.DateField(verbose_name='Event Date')),
                ('event_geocode', geoposition.fields.GeopositionField(blank=True, max_length=42, null=True, verbose_name='GEO Code')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Event End Date')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Event Location')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.PositiveIntegerField(blank=True, max_length=5, null=True, verbose_name='Zip Code')),
                ('rule', models.CharField(choices=[('Submission Only', 'Submission Only'), ('Points', 'Points'), ('Time Limit', 'Time Limit')], default='Points', max_length=25, verbose_name='Rules')),
                ('bracket', models.CharField(choices=[('Single Elimination', 'Single Elimination'), ('Double Elimination', 'Double Elimination'), ('Round Robin', 'Round Robin')], default='Round Robin', max_length=25, verbose_name='Brackets')),
                ('kids_special_formats', models.CharField(choices=[('Single Elimination', 'Single Elimination'), ('Double Elimination', 'Double Elimination'), ('Round Robin', 'Round Robin')], default='Round Robin', max_length=25, verbose_name='Kids Special Format')),
                ('kids_special_rules', models.CharField(choices=[('Submission Only', 'Submission Only'), ('Points', 'Points'), ('Time Limit', 'Time Limit')], default='Points', max_length=25, verbose_name='Kids Special Rules')),
                ('gi', models.BooleanField(default=False, verbose_name='GI')),
                ('nogi', models.BooleanField(default=False, verbose_name='NOGI')),
                ('kids', models.BooleanField(default=False, verbose_name='KIDS')),
                ('pro', models.BooleanField(default=False, verbose_name='PRO')),
                ('purse', models.BooleanField(default=False, verbose_name='PURSE PRIZE')),
                ('absolute', models.BooleanField(default=False, verbose_name='ABSOLUTE')),
                ('adults', models.BooleanField(default=False, verbose_name='ADULTS')),
                ('kids_special_format', models.BooleanField(default=False, verbose_name='KIDS')),
                ('cost', models.PositiveIntegerField(blank=True, max_length=5, null=True, verbose_name='Event Ticket Cost')),
                ('predate', models.DateField(blank=True, null=True, verbose_name='Event Pre Date')),
                ('cost_late', models.PositiveIntegerField(blank=True, max_length=5, null=True, verbose_name='Late Cost')),
                ('cutoff_date', models.DateField(blank=True, null=True, verbose_name='Cut-off Date')),
                ('event_description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Event Description')),
                ('small_image', models.ImageField(default='documents/no-img.jpeg', upload_to='documents', verbose_name='Event Image(Small)')),
                ('large_image', models.ImageField(default='documents/no-img.jpeg', upload_to='documents', verbose_name='Event Image(Large)')),
                ('added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data Added')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Data Updated')),
            ],
            options={
                'verbose_name_plural': 'Event Details',
            },
        ),
        migrations.CreateModel(
            name='Promoter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promoter_name', models.CharField(max_length=50, verbose_name='Promoter Name')),
                ('promoter_logo', models.ImageField(default='documents/no-img.jpeg', upload_to='documents', verbose_name='Promoter Logo')),
                ('promoter_logo_large', models.ImageField(default='documents/no-img.jpeg', upload_to='documents', verbose_name='Promoter Logo(Large)')),
                ('promoter_web', models.URLField(blank=True, verbose_name='Promoter Website')),
            ],
            options={
                'verbose_name_plural': 'Promoter Details',
            },
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='event_promoter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowlendercms.Promoter', verbose_name='Promoter Name'),
        ),
    ]
