# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-29 01:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flowlendercms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.PositiveIntegerField(max_length=5)),
                ('geo_code', models.CharField(max_length=50)),
                ('rule', models.CharField(choices=[('Submission Only', 'Submission Only'), ('Points', 'Points'), ('Time Limit', 'Time Limit')], default='Points', max_length=16)),
                ('bracket', models.CharField(choices=[('Single Elimination', 'Single Elimination'), ('Double Elimination', 'Double Elimination'), ('Round Robin', 'Round Robin')], default='Round Robin', max_length=16)),
                ('gi', models.BooleanField(default=False)),
                ('nogi', models.BooleanField(default=False)),
                ('kids', models.BooleanField(default=False)),
                ('pro', models.BooleanField(default=False)),
                ('purse', models.BooleanField(default=False)),
                ('absolute', models.BooleanField(default=False)),
                ('adults', models.BooleanField(default=False)),
                ('kids_special_rules', models.CharField(choices=[('Submission Only', 'Submission Only'), ('Points', 'Points'), ('Time Limit', 'Time Limit')], default='Points', max_length=16)),
                ('kids_special_format', models.CharField(choices=[('Single Elimination', 'Single Elimination'), ('Double Elimination', 'Double Elimination'), ('Round Robin', 'Round Robin')], default='Round Robin', max_length=16)),
                ('cost', models.PositiveIntegerField(max_length=5)),
                ('predate', models.DateField()),
                ('cost_late', models.PositiveIntegerField(max_length=5)),
                ('cutof_date', models.DateField()),
                ('event_description', models.TextField(max_length=50)),
                ('small_image', models.ImageField(upload_to='documents')),
                ('large_image', models.ImageField(upload_to='documents')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timein', models.TimeField()),
                ('timeout', models.TimeField()),
                ('bio', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Promotor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotor_name', models.CharField(max_length=50)),
                ('promotor_logo', models.ImageField(upload_to='documents')),
                ('promotor_logo_large', models.ImageField(upload_to='documents')),
                ('promotor_web', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Apply',
        ),
        migrations.DeleteModel(
            name='Contect',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='New',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='ammount_request',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='credit_score',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='debit_for',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='debit_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='promoter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowlendercms.Promotor'),
        ),
    ]
