# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-29 02:19
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flowlendercms', '0002_auto_20160629_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetail',
            name='geo_code',
            field=geoposition.fields.GeopositionField(max_length=42),
        ),
    ]
