# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-29 02:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowlendercms', '0003_auto_20160629_0219'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Promotor',
            new_name='Promoter',
        ),
        migrations.DeleteModel(
            name='ClientDetail',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RenameField(
            model_name='eventdetail',
            old_name='cutof_date',
            new_name='cutoff_date',
        ),
        migrations.RenameField(
            model_name='promoter',
            old_name='promotor_logo',
            new_name='promoter_logo',
        ),
        migrations.RenameField(
            model_name='promoter',
            old_name='promotor_logo_large',
            new_name='promoter_logo_large',
        ),
        migrations.RenameField(
            model_name='promoter',
            old_name='promotor_name',
            new_name='promoter_name',
        ),
        migrations.RenameField(
            model_name='promoter',
            old_name='promotor_web',
            new_name='promoter_web',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
