# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-29 03:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flowlendercms', '0004_auto_20160629_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetail',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 29, 3, 15, 30, 855983, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 29, 3, 15, 46, 400021, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventdetail',
            name='bracket',
            field=models.CharField(choices=[('Single Elimination', 'Single Elimination'), ('Double Elimination', 'Double Elimination'), ('Round Robin', 'Round Robin')], default='Round Robin', max_length=25),
        ),
        migrations.AlterField(
            model_name='eventdetail',
            name='event_description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='eventdetail',
            name='kids_special_format',
            field=models.CharField(choices=[('Single Elimination', 'Single Elimination'), ('Double Elimination', 'Double Elimination'), ('Round Robin', 'Round Robin')], default='Round Robin', max_length=25),
        ),
        migrations.AlterField(
            model_name='eventdetail',
            name='kids_special_rules',
            field=models.CharField(choices=[('Submission Only', 'Submission Only'), ('Points', 'Points'), ('Time Limit', 'Time Limit')], default='Points', max_length=25),
        ),
        migrations.AlterField(
            model_name='eventdetail',
            name='rule',
            field=models.CharField(choices=[('Submission Only', 'Submission Only'), ('Points', 'Points'), ('Time Limit', 'Time Limit')], default='Points', max_length=25),
        ),
    ]
